module.exports = {
    endOfLine: "lf",
    semi: true,
    singleQuote: false,
    tabWidth: 4,
    trailingComma: "es5",
    importOrder: [
        "^(react/(.*)$)|^(react$)",
        "^(next/(.*)$)|^(next$)",
        "<THIRD_PARTY_MODULES>",
        "",
        "^types$",
        "^@/app/(.*)$",
        "^@/processes/(.*)$",
        "^@/pages/(.*)$",
        "^@/widgets/(.*)$",
        "^@/features/(.*)$",
        "^@/entities/(.*)$",
        "^@/shared/(.*)$",
        "",
        "^[./]",
    ],
    importOrderSeparation: false,
    importOrderSortSpecifiers: true,
    importOrderBuiltinModulesToTop: true,
    importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
    importOrderMergeDuplicateImports: true,
    importOrderCombineTypeAndValueImports: true,
    importOrderTypeScriptVersion: "5.0.0",
    importOrderCaseSensitive: false,
    plugins: [
        require.resolve("@ianvs/prettier-plugin-sort-imports"),
        require.resolve("prettier-plugin-tailwindcss"),
    ],
};
