import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { cn } from "@/shared/lib/utils";

const interSans = Inter({
    variable: "--font-inter-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "bg-background text-foreground min-h-screen font-sans antialiased",
                    interSans.variable
                )}
            >
                <div className="container mx-auto">
                    <main className="max-w-container mb-md flex h-full w-full flex-col items-baseline justify-between gap-10">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
